package com.abc.greendaoexample.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.abc.greendaoexample.db.User;
import com.abc.greendaoexample.db.Repo;

import com.abc.greendaoexample.db.UserDao;
import com.abc.greendaoexample.db.RepoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig repoDaoConfig;

    private final UserDao userDao;
    private final RepoDao repoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repoDaoConfig = daoConfigMap.get(RepoDao.class).clone();
        repoDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        repoDao = new RepoDao(repoDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Repo.class, repoDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        repoDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RepoDao getRepoDao() {
        return repoDao;
    }

}
